spring.application.name=citasmedicas

spring.datasource.url=jdbc:postgresql://ep-twilight-hat-b5cvelo8-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_egPiWk65ocxf
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=9a785f76b92f9d6b45a2c418728d8b9916d10c2826cf8d42398d8916d7a421b5
jwt.expiration=86400000